In [2]:
import pandas as pd
import numpy as np

In [3]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import roc_auc_score, confusion_matrix

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [4]:
from sklearn.utils import resample

In [5]:
def full_path(path: str) -> str:
    path_to_project = 'C:\\Users\\Arseniy\\Documents\\Skillbox\\diploma_ML\\'
    return path_to_project + path

In [6]:
df = pd.read_parquet('/kaggle/input/res-08/res_08.pq')
df

,is_zero_loans5,is_zero_loans530,is_zero_loans3060,is_zero_loans6090,is_zero_loans90,is_zero_util,is_zero_over2limit,is_zero_maxover2limit,pclose_flag,fclose_flag,...,enc_loans_credit_type_2,enc_loans_credit_type_3,enc_loans_credit_type_4,enc_loans_credit_type_5,enc_loans_credit_type_6,enc_loans_credit_type_7,rn_max,credit_history_length_max,num_loan_months_max,frac_loan_months_max
index,,,,,,,,,,,,,,,,,,,,,
0,9,10,10,10,10,6,9,9,1,2,...,0,2,7,0,0,0,10,23.0,1,0.083333
1,12,10,12,12,11,10,12,11,1,2,...,0,3,8,0,0,0,14,24.0,2,0.285714
2,3,2,2,2,3,1,3,2,2,2,...,0,2,1,0,0,0,3,23.0,8,0.521739
3,15,15,15,15,15,8,14,14,5,6,...,0,4,9,1,0,0,15,24.0,0,0.000000
4,1,1,1,1,1,1,1,1,1,1,...,0,1,0,0,0,0,1,0.0,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999995,9,5,11,11,11,8,11,7,2,5,...,0,4,6,0,0,1,11,24.0,5,0.320000
2999996,12,13,12,13,13,9,11,11,5,4,...,0,4,8,0,0,1,13,24.0,2,0.333333
2999997,9,7,10,10,10,6,10,9,1,1,...,0,3,7,0,0,0,10,24.0,6,0.545455
2999998,5,5,4,4,4,1,4,4,2,1,...,0,2,2,0,0,0,5,6.0,1,1.000000
2999999,11,8,11,12,12,8,11,10,2,1,...,0,3,9,0,0,0,12,24.0,5,0.454545

In [7]:
target = pd.read_csv('/kaggle/input/target/train_target.csv').flag
target

0          0
1          0
2          0
3          0
4          0
          ..
2999995    0
2999996    0
2999997    0
2999998    0
2999999    0
Name: flag, Length: 3000000, dtype: int64

In [8]:
df.loc[:,'target'] = target
df.head()

,is_zero_loans5,is_zero_loans530,is_zero_loans3060,is_zero_loans6090,is_zero_loans90,is_zero_util,is_zero_over2limit,is_zero_maxover2limit,pclose_flag,fclose_flag,...,enc_loans_credit_type_3,enc_loans_credit_type_4,enc_loans_credit_type_5,enc_loans_credit_type_6,enc_loans_credit_type_7,rn_max,credit_history_length_max,num_loan_months_max,frac_loan_months_max,target
index,,,,,,,,,,,,,,,,,,,,,
0,9,10,10,10,10,6,9,9,1,2,...,2,7,0,0,0,10,23.0,1,0.083333,0
1,12,10,12,12,11,10,12,11,1,2,...,3,8,0,0,0,14,24.0,2,0.285714,0
2,3,2,2,2,3,1,3,2,2,2,...,2,1,0,0,0,3,23.0,8,0.521739,0
3,15,15,15,15,15,8,14,14,5,6,...,4,9,1,0,0,15,24.0,0,0.000000,0
4,1,1,1,1,1,1,1,1,1,1,...,1,0,0,0,0,1,0.0,0,0.000000,0

In [9]:
df.loc[:,'target'] = target
df.head()

,is_zero_loans5,is_zero_loans530,is_zero_loans3060,is_zero_loans6090,is_zero_loans90,is_zero_util,is_zero_over2limit,is_zero_maxover2limit,pclose_flag,fclose_flag,...,enc_loans_credit_type_3,enc_loans_credit_type_4,enc_loans_credit_type_5,enc_loans_credit_type_6,enc_loans_credit_type_7,rn_max,credit_history_length_max,num_loan_months_max,frac_loan_months_max,target
index,,,,,,,,,,,,,,,,,,,,,
0,9,10,10,10,10,6,9,9,1,2,...,2,7,0,0,0,10,23.0,1,0.083333,0
1,12,10,12,12,11,10,12,11,1,2,...,3,8,0,0,0,14,24.0,2,0.285714,0
2,3,2,2,2,3,1,3,2,2,2,...,2,1,0,0,0,3,23.0,8,0.521739,0
3,15,15,15,15,15,8,14,14,5,6,...,4,9,1,0,0,15,24.0,0,0.000000,0
4,1,1,1,1,1,1,1,1,1,1,...,1,0,0,0,0,1,0.0,0,0.000000,0

In [10]:
train, test = train_test_split(df, stratify=df.target, test_size=0.2, random_state=44)

In [11]:
train.shape

(2400000, 385)

In [12]:
test.shape

(600000, 385)

## Downsampling

In [13]:
train_maj = train[train.target == 0] 
train_min = train[train.target == 1]
train_min.shape

(85154, 385)

In [14]:
train_downs = resample(train_maj, replace=False, n_samples=len(train_min), random_state=44)
train_downs

,is_zero_loans5,is_zero_loans530,is_zero_loans3060,is_zero_loans6090,is_zero_loans90,is_zero_util,is_zero_over2limit,is_zero_maxover2limit,pclose_flag,fclose_flag,...,enc_loans_credit_type_3,enc_loans_credit_type_4,enc_loans_credit_type_5,enc_loans_credit_type_6,enc_loans_credit_type_7,rn_max,credit_history_length_max,num_loan_months_max,frac_loan_months_max,target
index,,,,,,,,,,,,,,,,,,,,,
644196,10,10,10,10,10,8,10,10,0,2,...,2,6,0,0,0,10,24.0,0,0.000000,0
2971099,7,7,6,6,6,6,7,7,0,1,...,2,5,0,0,1,8,24.0,2,0.400000,0
500525,1,1,2,2,2,1,2,1,0,1,...,1,1,0,0,0,2,24.0,1,0.200000,0
740875,21,21,21,21,21,17,19,19,0,1,...,3,17,0,0,0,21,24.0,0,0.000000,0
1852306,5,5,5,5,5,4,4,4,0,4,...,5,0,0,0,0,5,24.0,0,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555734,10,10,11,11,11,8,11,10,5,4,...,1,7,0,0,0,11,23.0,1,0.111111,0
429512,2,2,2,2,2,0,2,2,0,1,...,0,1,0,0,0,2,9.0,0,0.000000,0
2730644,15,17,16,16,16,13,16,16,2,3,...,5,11,0,0,0,17,24.0,8,0.400000,0
1833571,2,2,2,2,2,2,2,2,0,0,...,1,0,0,0,0,2,5.0,0,0.000000,0
1244517,3,1,3,3,3,2,3,2,0,1,...,1,1,1,0,0,3,9.0,1,0.200000,0

In [15]:
train = pd.concat((train_downs, train_min), ignore_index=True).sample(frac=1.0)
train

,is_zero_loans5,is_zero_loans530,is_zero_loans3060,is_zero_loans6090,is_zero_loans90,is_zero_util,is_zero_over2limit,is_zero_maxover2limit,pclose_flag,fclose_flag,...,enc_loans_credit_type_3,enc_loans_credit_type_4,enc_loans_credit_type_5,enc_loans_credit_type_6,enc_loans_credit_type_7,rn_max,credit_history_length_max,num_loan_months_max,frac_loan_months_max,target
105813,21,20,21,21,21,16,20,19,4,5,...,6,11,0,0,1,21,24.0,1,0.050000,1
93642,5,2,3,4,4,4,5,3,0,0,...,1,4,0,0,0,5,24.0,4,0.666667,1
136524,6,6,6,6,6,3,6,6,0,3,...,4,4,0,0,0,8,24.0,2,0.125000,1
90393,11,10,11,11,11,6,9,8,4,4,...,3,6,2,0,1,12,24.0,1,0.058824,1
93859,4,5,3,5,4,3,6,6,0,2,...,0,6,0,0,0,6,24.0,13,0.800000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169734,7,7,7,7,8,8,8,8,2,3,...,3,3,2,0,0,8,18.0,2,0.166667,1
72921,18,18,18,18,18,18,18,18,1,1,...,0,6,12,0,0,18,5.0,0,0.000000,0
153677,16,9,18,19,19,18,19,10,3,0,...,2,17,0,0,0,19,24.0,11,0.785714,1
21078,4,4,5,5,5,3,5,4,2,4,...,4,1,0,0,0,5,20.0,3,0.214286,0
15860,2,2,2,2,2,0,2,2,0,0,...,0,2,0,0,0,2,5.0,0,0.000000,0

In [16]:
train.target.value_counts()

target
1    85154
0    85154
Name: count, dtype: int64

In [17]:
X_train, y_train = train.drop(columns='target'), train['target']

In [18]:
X_test, y_test = test.drop(columns='target'), test['target']

In [19]:
y_train

105813    1
93642     1
136524    1
90393     1
93859     1
         ..
169734    1
72921     0
153677    1
21078     0
15860     0
Name: target, Length: 170308, dtype: int64

In [20]:
df.drop(index=df.index, inplace=True)
train.drop(index=train.index, inplace=True)
test.drop(index=test.index, inplace=True)
train_downs.drop(index=train_downs.index, inplace=True)
train_maj.drop(index=train_maj.index, inplace=True)
train_min.drop(index=train_min.index, inplace=True)

### MLP torch

In [62]:
import torch
from torch import nn
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [63]:
torch.cuda.is_available()

True

In [64]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cuda', index=0)

In [65]:
class MyDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.from_numpy(X.astype(np.float32))
        self.y = torch.from_numpy(y.astype(np.float32))
        self.X.to(torch.device("cuda:0"))
        self.y.to(torch.device("cuda:0"))
        
    def __getitem__(self, index):
        return self.X[index], self.y[index]
    
    def __len__(self):
        return self.X.shape[0]

# Инициализируем тренировочный torch.dataset
train_dataset = MyDataset(X_train.to_numpy(), y_train.to_numpy())

# Преобразуем тестовую выборку в torch-тензоры всю целиком
X_test_tensor = torch.from_numpy(X_test.to_numpy().astype(np.float32)).to(device)
y_test_tensor = torch.from_numpy(y_test.to_numpy().astype(np.float32)).to(device)
X_train_tensor = torch.from_numpy(X_train.to_numpy().astype(np.float32)).to(device)
y_train_tensor = torch.from_numpy(y_train.to_numpy().astype(np.float32)).to(device)

In [135]:
# Пусть размер батча у нас равен
batch_size = 512

# Создайте Dataloader для тренировочной выборки на основе экземпляра train_dataset
train_dataloader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True,
)

In [136]:
class ClassificationNet(nn.Module):
    def __init__(self, input_dim:int, hidden_dim:tuple, output_dim:int):
        super().__init__()
        
        self.hidden_list = []
        self.func_list = []
        
        prev_dim = input_dim
        for i, dim in enumerate(hidden_dim, 1):
            self.hidden_list.append(nn.Linear(prev_dim, dim))
            self.__setattr__(f"hidden{i}", self.hidden_list[-1])
            prev_dim = dim
            
            self.func_list.append(nn.ReLU())
            self.__setattr__(f"f{i}", self.func_list[-1])
        
        self.output = nn.Linear(prev_dim, output_dim)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x):
#         x.to(torch.device("cuda:0"))
        for hidden, func in zip(self.hidden_list, self.func_list):
            x = func(hidden(x))
#             x.to(torch.device("cuda:0"))
        
        x = self.sigmoid(self.output(x))
#         x.to(torch.device("cuda:0"))
        
        return x
    
    def predict(self, X):
        predict = [int(x > 0.5) for x in self(X)]
        return predict


# Объявляем экземпляр класса нейронной сети
net = ClassificationNet(X_train.shape[1], (2048, 512, 128, 32), 1).to(device)

net

ClassificationNet(
  (hidden1): Linear(in_features=384, out_features=2048, bias=True)
  (f1): ReLU()
  (hidden2): Linear(in_features=2048, out_features=512, bias=True)
  (f2): ReLU()
  (hidden3): Linear(in_features=512, out_features=128, bias=True)
  (f3): ReLU()
  (hidden4): Linear(in_features=128, out_features=32, bias=True)
  (f4): ReLU()
  (output): Linear(in_features=32, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [137]:
# Сюда будем сохранять значение roc_auc на тестовой выборке
# после каждой эпохи обучения
auc_test = []

In [142]:
# функция потерь
loss_fn = nn.BCELoss()

# Создаём оптимизатор
optimizer = torch.optim.SGD(net.parameters(), lr=0.001)

# Делаем n эпох
num_epochs = 20

In [143]:
# Тренировочный цикл
for epoch in range(num_epochs):
    print(f"Epoch {epoch}: ", end='')
    for X, y in train_dataloader:
        X = X.to(device)
        y = y.to(device)
        pred = net(X).to(device)
        loss = loss_fn(pred, y.unsqueeze(-1))
        # print(loss.item())
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
  

    with torch.no_grad():
        # Конец эпохи: считаем функцию потерь на тестовой выборке, 
        # сохраняем в список, чтобы потом нарисовать график
        pred_proba = net(X_test_tensor).to(device)
        loss = loss_fn(
            pred_proba,
            y_test_tensor.unsqueeze(-1)
        ).item()
        auc = roc_auc_score(y_test, pred_proba.cpu())
        auc_test.append(auc)
        print(f'loss {loss}, auc {auc}')

Epoch 0: loss 0.5875165462493896, auc 0.7588366937590975
Epoch 1: loss 0.5918481945991516, auc 0.7587580104541813
Epoch 2: loss 0.5949674844741821, auc 0.7589438213642405
Epoch 3: loss 0.5893176794052124, auc 0.7588414625746098
Epoch 4: loss 0.5869989395141602, auc 0.7587769371321156
Epoch 5: loss 0.5854824185371399, auc 0.7589042579314218
Epoch 6: loss 0.5909606218338013, auc 0.7587317596061618
Epoch 7: loss 0.5936831831932068, auc 0.7585735057531301
Epoch 8: loss 0.5944738388061523, auc 0.7585327297018445
Epoch 9: loss 0.5879764556884766, auc 0.7587472806192782
Epoch 10: loss 0.593052327632904, auc 0.758526058311578
Epoch 11: loss 0.5778532028198242, auc 0.7586199758513092
Epoch 12: loss 0.593639075756073, auc 0.7586039971536604
Epoch 13: loss 0.5834892988204956, auc 0.758593733282765
Epoch 14: loss 0.5879489183425903, auc 0.7585215776136938
Epoch 15: loss 0.5991600751876831, auc 0.7584821534708738
Epoch 16: loss 0.5872722864151001, auc 0.7585583259842761
Epoch 17: loss 0.5920533537864685, auc 0.7584485527620437
Epoch 18: loss 0.6018286347389221, auc 0.7585495428407436
Epoch 19: loss 0.5781649947166443, auc 0.7586676051572214

Оценка качества предсказания:

In [144]:
with torch.no_grad():
    pred_net = net.predict(X_test_tensor)
    pred_net[:10]

In [145]:
confusion_matrix(y_test, pred_net)

array([[392724, 185988],
       [  6297,  14991]])

In [146]:
with torch.no_grad():
    print(roc_auc_score(y_test, net(X_test_tensor).cpu()))

0.7586676051572214

In [147]:
torch.save(net, 'nn_auc7587.pt')